/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#b87500",
        "on-primary-container": "#79849b",
        "surface-container-highest": "#e0e3e5",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#6bd8cb",
        "inverse-on-surface": "#eff1f3",
        "on-primary": "#ffffff",
        "surface-tint": "#535f74",
        "tertiary-container": "#2a1700",
        "outline-variant": "#c5c6cd",
        "surface-container": "#eceef0",
        "surface-bright": "#f7f9fb",
        "primary-container": "#101c2e",
        "tertiary-fixed": "#ffddb8",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#45474c",
        "on-background": "#191c1e",
        "inverse-surface": "#2d3133",
        "primary-fixed-dim": "#bbc7df",
        "on-error-container": "#93000a",
        "secondary": "#006a61",
        "inverse-primary": "#bbc7df",
        "on-secondary-container": "#006f66",
        "on-secondary-fixed": "#00201d",
        "background": "#f7f9fb",
        "primary": "#000000",
        "surface-container-low": "#f2f4f6",
        "secondary-fixed": "#89f5e7",
        "surface": "#f7f9fb",
        "secondary-container": "#86f2e4",
        "surface-variant": "#e0e3e5",
        "on-tertiary-fixed": "#2a1700",
        "surface-container-high": "#e6e8ea",
        "on-surface": "#191c1e",
        "tertiary": "#000000",
        "on-primary-fixed": "#101c2e",
        "tertiary-fixed-dim": "#ffb95f",
        "primary-fixed": "#d7e3fc",
        "surface-dim": "#d8dadc",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#005049",
        "outline": "#75777d",
        "error": "#ba1a1a",
        "on-primary-fixed-variant": "#3c475b",
        "on-tertiary-fixed-variant": "#653e00",
        "on-secondary": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
}
